# Terraform Configuration generated by ArchGen AI
# Target Provider: Azure (azurerm)

terraform {
  required_version = ">= 1.3.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.5"
    }
  }
}

provider "azurerm" {
  features {}
}

# Unique suffix for strict Azure global naming
resource "random_string" "suffix" {
  length  = 6
  special = false
  upper   = false
}

# Core Resource Group for scoping deployment
resource "azurerm_resource_group" "rg" {
  name     = "rg-${var.project_name}-${var.environment}"
  location = var.location
}

# ==========================================
# SHARED INFRASTRUCTURE (Defined Once)
# ==========================================
# Container App Environment for all Backend Microservices
resource "azurerm_container_app_environment" "app_env" {
  name                = "cae-${var.project_name}-${var.environment}"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
}

resource "azurerm_virtual_network" "vnet" {
  name                = "vnet-${var.project_name}-${var.environment}"
  resource_group_name = azurerm_resource_group.rg.name
  location            = azurerm_resource_group.rg.location
  address_space       = ["10.0.0.0/16"]
}

# ==========================================
# SERVICE: Frontend (FrontendNode)
# ==========================================
# static Web App for SPA hosting (React/Vue/Next.js)
resource "azurerm_static_web_app" "spa_frontend_frontendno" {
  name                = "stt-${substr(var.project_name, 0, 8)}-fe-${substr(var.environment, 0, 4)}-frontendno"
  resource_group_name = azurerm_resource_group.rg.name
  location            = "eastus2" # Azure Static Web Apps requires specific global hubs
}


# ==========================================
# SERVICE: Backend (BackendNode)
# ==========================================
# Container App Compute
resource "azurerm_container_app" "api_backend_backendnod" {
  name                         = "ca-${substr(var.project_name, 0, 8)}-be-${substr(var.environment, 0, 4)}-backendnod"
  container_app_environment_id = azurerm_container_app_environment.app_env.id
  resource_group_name          = azurerm_resource_group.rg.name
  revision_mode                = "Single"

  template {
    container {
      name   = "api-service"
      image  = "mcr.microsoft.com/azuredocs/aci-helloworld:latest"
      cpu    = "0.25"
      memory = "0.5Gi"
      
      env {
        name  = "ENVIRONMENT"
        value = var.environment
      }

      # Dynamic Environment Bindings based on visual edge connections!
      env {
        name  = "DATABASE_URL"
        value = "postgresql://dbadmin:${var.db_password}@psql-${substr(var.project_name, 0, 8)}-db-${substr(var.environment, 0, 4)}-database00.postgres.database.azure.com/appdb"
      }
    }
  }

  ingress {
    external_enabled = true
    target_port      = 80
    traffic_weight {
      percentage      = 100
      latest_revision = true
    }
  }
}


# ==========================================
# SERVICE: Storage (StorageNode)
# ==========================================
# General Purpose Block Storage for documents and binary files
resource "azurerm_storage_account" "blob_storage_storagenod" {
  name                     = lower("st${substr(var.project_name, 0, 6)}${substr(var.environment, 0, 3)}${random_string.suffix.result}storagenod")
  resource_group_name      = azurerm_resource_group.rg.name
  location                 = azurerm_resource_group.rg.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_storage_container" "upload_bucket_storagenod" {
  name                  = "media"
  storage_account_name  = azurerm_storage_account.blob_storage_storagenod.name
  container_access_type = "blob"
}


# ==========================================
# SERVICE: Database (DatabaseNode)
# ==========================================
# Flexible PostgreSQL Server for relational transactional security
resource "azurerm_postgresql_flexible_server" "postgres_db_database00" {
  name                   = lower("psql-${substr(var.project_name, 0, 8)}-db-${substr(var.environment, 0, 4)}-database00")
  resource_group_name    = azurerm_resource_group.rg.name
  location               = azurerm_resource_group.rg.location
  version                = "14"
  administrator_login    = "dbadmin"
  administrator_password = var.db_password
  sku_name               = "GP_Standard_D2ds_v4"
  storage_mb             = 32768
  backup_retention_days  = 7
}

resource "azurerm_postgresql_flexible_server_database" "main_db_database00" {
  name      = "appdb"
  server_id = azurerm_postgresql_flexible_server.postgres_db_database00.id
  collation = "en_US.utf8"
  charset   = "utf8"
}


# ==========================================
# SERVICE: Key Vault (SecurityNode)
# ==========================================
# Key Vault for system secret generation and certificate storage
resource "azurerm_key_vault" "key_vault_keyvaultse" {
  name                        = "kv-${substr(var.project_name, 0, 6)}-${substr(var.environment, 0, 3)}-keyvaultse"
  location                    = azurerm_resource_group.rg.location
  resource_group_name         = azurerm_resource_group.rg.name
  enabled_for_disk_encryption = true
  tenant_id                   = "00000000-0000-0000-0000-000000000000" # Placeholder UUID for configuration
  sku_name                    = "standard"
}

